### ISSUE TITLE
Desklet Crashes On Load - Cinnamon 3.8.9, Mint 19

### ISSUE THREAD

**Issue by EvilSupahFly** [tipichris/bbcwx#35]
Running Mint 19 x64 with Cinnamon 3.8.9 after upgrading from Mint 18, and the weather app crashes on load. Tried uninstalling and reinstalling, but it still crashes. Here's from the log (~/.xsession-errors):

```<----------------
anonymous/MyDesklet.prototype._getIconMeta@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:521:1
anonymous/MyDesklet.prototype._initIcons@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:496:22
anonymous/MyDesklet.prototype._setDerivedValues@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:459:5
anonymous/MyDesklet.prototype.initForecast@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:238:5
anonymous/MyDesklet.prototype._init@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:194:7
MyDesklet@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:92:3
main@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:3601:17
_createDesklets@/usr/share/cinnamon/js/ui/deskletManager.js:316:19
_loadDesklet@/usr/share/cinnamon/js/ui/deskletManager.js:284:23
_onEnabledDeskletsChanged@/usr/share/cinnamon/js/ui/deskletManager.js:237:9
---------------->

(cinnamon:1605): Cjs-WARNING **: 18:19:27.930: JS ERROR: ReferenceError: assignment to undeclared variable prop
anonymous/MyDesklet.prototype._getIconMeta@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:521:1
anonymous/MyDesklet.prototype._initIcons@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:496:22
anonymous/MyDesklet.prototype._setDerivedValues@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:459:5
anonymous/MyDesklet.prototype.updateStyle@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:533:5
bind/<@resource:///org/cinnamon/cjs/modules/lang.js:97:16
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:580:40

/tmp/tmpwgazbdbu/bbcwx@oak-wood.co.uk/po/es.po:7: warning: header field 'Language-Team' still has the initial default value
Cjs-Message: 18:20:25.153: JS LOG: [LookingGlass/info] Installing settings for bbcwx@oak-wood.co.uk
Cjs-Message: 18:20:25.155: JS LOG: [LookingGlass/info] Settings successfully installed for bbcwx@oak-wood.co.uk
Cjs-Message: 18:20:25.163: JS LOG: [LookingGlass/error] assignment to undeclared variable prop
Cjs-Message: 18:20:25.163: JS LOG: [LookingGlass/trace] 
<----------------
anonymous/MyDesklet.prototype._getIconMeta@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:521:1
anonymous/MyDesklet.prototype._initIcons@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:496:22
anonymous/MyDesklet.prototype._setDerivedValues@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:459:5
anonymous/MyDesklet.prototype.initForecast@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:238:5
anonymous/MyDesklet.prototype._init@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:194:7
MyDesklet@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:92:3
main@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:3601:17
_createDesklets@/usr/share/cinnamon/js/ui/deskletManager.js:316:19
_loadDesklet@/usr/share/cinnamon/js/ui/deskletManager.js:284:23
_onEnabledDeskletsChanged@/usr/share/cinnamon/js/ui/deskletManager.js:237:9
---------------->

(cinnamon:1605): St-WARNING **: 18:20:37.360: Did not find color property '-panel-corner-inner-border-color'

(cinnamon:1605): St-WARNING **: 18:20:37.360: Did not find color property '-panel-corner-outer-border-color'

(cinnamon:1605): St-WARNING **: 18:20:37.361: Did not find color property '-panel-corner-inner-border-color'

(cinnamon:1605): St-WARNING **: 18:20:37.361: Did not find color property '-panel-corner-outer-border-color'

(cinnamon:1605): Cjs-CRITICAL **: 18:20:39.323: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1605): Cjs-CRITICAL **: 18:20:39.323: The offending signal was destroy on StBin 0x55f27ff3ff60.
== Stack trace for context 0x55f27c2d0000 ==

(cinnamon:1605): Cjs-CRITICAL **: 18:20:39.324: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1605): Cjs-CRITICAL **: 18:20:39.324: The offending signal was destroy on StBin 0x55f27ff4afc0.
== Stack trace for context 0x55f27c2d0000 ==

(cinnamon:1605): Cjs-CRITICAL **: 18:20:39.324: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(cinnamon:1605): Cjs-CRITICAL **: 18:20:39.324: The offending signal was destroy on StBin 0x55f27ff4bf80.
== Stack trace for context 0x55f27c2d0000 ==
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 124, in check_settings
    self.settings = self.get_settings()
  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 139, in get_settings
    file = open(self.filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seann/.cinnamon/configs/bbcwx@oak-wood.co.uk/15.json'
Gtk-Message: 18:35:00.404: GtkDialog mapped without a transient parent. This is discouraged.

(cinnamon:1605): Cjs-WARNING **: 18:35:09.266: JS ERROR: ReferenceError: assignment to undeclared variable prop
anonymous/MyDesklet.prototype._getIconMeta@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:521:1
anonymous/MyDesklet.prototype._initIcons@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:496:22
anonymous/MyDesklet.prototype._setDerivedValues@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:459:5
anonymous/MyDesklet.prototype.initForecast@/home/seann/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:238:5
bind/<@resource:///org/cinnamon/cjs/modules/lang.js:97:16
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:580:40
```

**Comment by clarktrip1** [comment]
I upgraded from Mint 18.3.  Desklet does not appear.  I don't get the FileNotFoundError errors in .xsession-errors, but the final block is the same.  I uninstalled and reinstalled and get this:

```
(cinnamon:2651): Cjs-WARNING **: 09:50:04.752: JS ERROR: ReferenceError: assignment to undeclared variable prop
anonymous/MyDesklet.prototype._getIconMeta@/home/cary/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:469:1
anonymous/MyDesklet.prototype._initIcons@/home/cary/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:444:22
anonymous/MyDesklet.prototype._setDerivedValues@/home/cary/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:407:5
anonymous/MyDesklet.prototype.redraw@/home/cary/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:585:5
anonymous/MyDesklet.prototype.displayOptsChange@/home/cary/.local/share/cinnamon/desklets/bbcwx@oak-wood.co.uk/desklet.js:579:5
bind/<@resource:///org/cinnamon/cjs/modules/lang.js:97:16
XletSettingsBase.prototype._checkSettings@/usr/share/cinnamon/js/ui/settings.js:580:40
```
